Traceback (most recent call last):
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import hydrodataset
------------------

----- stdout -----
Unexpected error: Configuration file not found: /home/runner/hydro_setting.yml
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mhydrodataset[39;00m

File [0;32m/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/hydrodataset/__init__.py:73[0m
[1;32m     70[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mUnexpected error: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     72[0m [38;5;66;03m# set some constants for hydrodataset[39;00m
[0;32m---> 73[0m ROOT_DIR [38;5;241m=[39m [43mSETTING[49m[[38;5;124m"[39m[38;5;124mlocal_data_path[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mdatasets-origin[39m[38;5;124m"[39m]
[1;32m     74[0m CACHE_DIR [38;5;241m=[39m Path(hydro_file[38;5;241m.[39mget_cache_dir())
[1;32m     77[0m [38;5;66;03m# set some constants for datasets[39;00m

[0;31mNameError[0m: name 'SETTING' is not defined

